#!/bin/sh /etc/rc.common
START=400
STOP=12
# The command(s) you want to run on start
start() {        
    sleep 3
    /usr/sbin/vpn-select
}
# The command(s) you want to run on stop
stop() {          
        #Nothing to do
}
