#!/bin/sh /etc/rc.common
START=100
STOP=12
# The command(s) you want to run on start
start() {        
    sleep 60
    /usr/sbin/vpn-select
}
# The command(s) you want to run on stop
stop() {          
        echo Nothing to do
}
