include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-config-mode-mesh-vpn-vpn-select
PKG_VERSION:=3

include $(TOPDIR)/../package/gluon.mk

define Package/gluon-config-mode-mesh-vpn-vpn-select
  TITLE:=Toggle mesh-vpn and bandwidth limit
  DEPENDS:=gluon-config-mode-core +gluon-mesh-vpn-core
endef

$(eval $(call BuildPackageGluon,gluon-config-mode-mesh-vpn-vpn-select))
